### ISSUE TITLE
The HLV diff has to run only on couchbase server versions >= 7.6.2

### ISSUE THREAD

**Issue by sumukhbhat2701** [couchbase/xdcrDiffer#108]
If the differ is run on clusters which don't have the bucket setting pruningWindow, it will error out and not proceed. 
```
xdcrDiffer.log:90:2024-05-11T15:03:56.158Z ERRO GOXDCR.BucketTopologySvc: BucketTopologySvcWatcher for local? false bucket rtest updating resulted in err Error looking up versionPruningWindowHrs from bucketInfo...
```

**Comment by darshan-na** [comment]
The issue was on the goxdcr side where in the remote bucket watcher would return a fatal error if PruningWindow is not an entry in the remote Bucket Info.
@Aditya-Sood  - Rectified this issue on goxdcr and difftool was checked on couchbase-server versions <7.6.2 with the latest goxdcr build including the bugfix and was found to be successful
